### ISSUE TITLE
Website tailwind design layout

### ISSUE THREAD

**Issue by Al-Ip** [marky291/procurator#1]
Minimal design
![Image](https://user-images.githubusercontent.com/43743759/178318537-96170eb1-d61a-438c-84f3-da97d2c392e7.jpg)

### To-do

1. Rough draft of components.
2. Decipher ancient scrolls of text.

**Comment by marky291** [comment]
<img width="1440" alt="Screenshot 2022-07-11 at 22 19 51" src="https://user-images.githubusercontent.com/5384515/178360373-a12cd1bf-9e39-46c7-ae0f-8354e91dd038.png">
