### ISSUE TITLE
Navigation to include Generator Menu Option

### ISSUE THREAD

**Issue by marky291** [marky291/procurator#23]
On the left hand side, the navigation should show a menu named 'generator'.

On the generator menu there should be a submenu with the following items:
- Content

This content page is the one we are working on and can include all the generators currently.

All other menu items should be removed.

**Comment by Al-Ip** [comment]
Which menu are you referring to?

**Comment by marky291** [comment]
> Referring to? ![image](https://user-images.githubusercontent.com/43743759/181916956-f244f125-7f23-4c59-8ebc-0411c9af28ad.png)

updated desc
