### ISSUE TITLE
Detect spam text 

### ISSUE THREAD

**Issue by Al-Ip** [marky291/procurator#38]
As a user, I want to be able to write a received SMS text message into a textbox. The result should display to the user whether or not the inputted SMS is spam or not.

Sperate from forge... maybe its own process?
Probably some machine learning model we can use.

**Comment by Al-Ip** [comment]
Will remove and use for another proj myself, so wont merge into master. Pull the branch if you wanna test it out its cool!

**Comment by marky291** [comment]
@Al-Ip Thank you for your contribution in this sprint
